### ISSUE TITLE
Trying To download older Nintendo games on Lutris. Its not working

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#168]
**Describe the bug**
I try to download Mario Cart 64 (I'm a fan), I use Lutris, but when I install it will tell me "Error Installing" 

**To Reproduce**
1. Download Mario Cart 64 off Lutris
2. Install
3. Get error message

**Expected behavior**
Mario to work

**Screenshots / Photos**
(ERROR MESSAGE COPIED AND PASTED)

Failed to retrieve libretro (mupen64plus_next) information

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(

  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 166, in install
    captured_super.install(install_ui_delegate, version, callback)

  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 480, in install
    raise RunnerInstallationError(_("Failed to retrieve {} ({}) information").format(self.name, version))

lutris.runners.RunnerInstallationError: Failed to retrieve libretro (mupen64plus_next) information

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 442, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 283, in install_runner
    raise ScriptingError(ex.message) from ex

lutris.installer.errors.ScriptingError: Failed to retrieve libretro (mupen64plus_next) information

I don't believe to have read this in the README, but am very sorry if it was already mentioned.

**Comment by FlappyChiken** [comment]
Help plz

**Comment by TheTruePerson** [comment]
since nobody is answering, i asked chatgpt. this will only help if the issue is unrelated to shimboot, though.



This issue seems to be related to the libretro core for mupen64plus_next not being retrieved during the installation process in Lutris. Here’s how you can troubleshoot and potentially resolve the problem:

Steps to Resolve:
Update Lutris:

Ensure that you’re using the latest version of Lutris. Use your package manager or download it from the [official Lutris website](https://lutris.net/).
Check Dependencies:

Verify that all required dependencies for libretro and mupen64plus_next are installed. On Debian-based systems, you might need to run:
bash
Copy code
sudo apt update
sudo apt install libretro-core-info mupen64plus
Install RetroArch:

Lutris often relies on RetroArch for libretro cores. Install RetroArch if it’s not already installed:
bash
Copy code
sudo apt install retroarch
Then, download the mupen64plus_next core directly within RetroArch by:
Opening RetroArch.
Navigating to Online Updater > Core Updater.
Finding and downloading Nintendo - Nintendo 64 (Mupen64Plus-Next).
Verify Core Availability:

If the mupen64plus_next core isn’t listed in RetroArch, it could be an issue with the server or package availability. Try downloading the core manually from the Libretro buildbot and placing it in the appropriate directory (usually ~/.config/retroarch/cores).
Run Lutris in Debug Mode:

Launch Lutris with debugging enabled to get more detailed error logs:
bash
Copy code
lutris -d
Try installing the game again and check for additional clues in the log output.
Manually Configure the Runner:

If the automated installation fails, you can manually configure Lutris to use RetroArch as a runner:
Add the game manually in Lutris.
Set Runner Options to RetroArch.
Provide the path to the downloaded mupen64plus_next core.
Check Network Connectivity:

Ensure your network isn’t blocking the Lutris servers or the Libretro buildbot. Use a VPN if necessary to bypass regional restrictions.
Reinstall Lutris Runners:

Sometimes reinstalling the runners resolves issues. Delete and re-download mupen64plus_next from Lutris:
bash
Copy code
lutris runners uninstall libretro
lutris runners install libretro
