### ISSUE TITLE
Unable to build image

### ISSUE THREAD

**Issue by SniverDaBest** [ading2210/shimboot#62]
**Describe the bug**
When I try and build an Alpine Linux XFCE image, it throws an error when trying to download the list of recovery images.

**To Reproduce**
1. Run `sudo ./build_complete.sh dedede distro=alpine desktop=xfce`
2. I get an error.

**Expected behavior**
I expect to build a shimboot image.

**Screenshots / Photos**
This is the error I get when bulding:
![Screenshot from 2024-09-06 20-07-26](https://github.com/user-attachments/assets/55e54a16-85cf-450a-84cc-c471541caded)

**Target Chrome OS Device (please complete the following information):**
 - Board Name dedede
 - Device Name drawcia
 - Shimboot version 1.2.1 

**Build Device (please complete the following information):**
 - OS: Fedora Workstation
 - Neofetch out
user@computer 
------------ 
OS: Fedora Linux 40 (Workstation Edition) x86_64 
Kernel: 6.10.6-200.fc40.x86_64 
Uptime: 57 mins 
Packages: 2898 (rpm), 66 (flatpak) 
Shell: zsh 5.9 
Resolution: 1280x1024, 1920x1080 
DE: GNOME 46.4 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: ptyxis-agent 
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
GPU: AMD ATI Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600 
Memory: 5732MiB / 15913MiB 
IP Address: XXX.XXX.XXX.XXX

**Additional context**
I have tried to compile through distrobox's debian, but it still didn't work. It threw a different issue, when doing things in the `/dev/` directory.

**Comment by Raf128** [comment]
Does this also happen if you attempt to build debian?

**Comment by Raf128** [comment]
scratch that try running with the quiet option

**Comment by SniverDaBest** [comment]
It happens no matter what. Even if I run with quiet, or build Debian Unstable/Bookworm, or Alpine.

**Comment by ading2210** [comment]
Can you run the build script with the `DEBUG=1` option? Like this: `sudo DEBUG=1 ./build_complete.sh`

**Comment by Raf128** [comment]
I might be going crazy but maybe try updating wget, idk how to do this on your distros but you should be able to figure it out

**Comment by Raf128** [comment]
it seems that if you are on fedora you can try apt-get install --only-upgrade wget

**Comment by ading2210** [comment]
Also, can you send the output of `wget --help | grep 'show-progress'`?

**Comment by SniverDaBest** [comment]
Here's the debug info:
```
++ export DEBUG=1
++ DEBUG=1
++ ANSI_CLEAR='\033[0m'
++ ANSI_BOLD='\033[1m'
++ ANSI_RED='\033[1;31m'
++ ANSI_GREEN='\033[1;32m'
++ ANSI_BLUE='\033[1;34m'
+ . ./image_utils.sh
+ assert_root
+ '[' 0 -ne 0 ']'
+ assert_args dedede
+ '[' -z dedede ']'
+ parse_args dedede distro=alpine desktop=xfce
+ declare -g -A args
+ for argument in "$@"
+ '[' dedede = -h ']'
+ '[' dedede = --help ']'
++ echo dedede
++ cut -f1 -d=
+ local key=dedede
+ local key_length=6
+ local value=
+ args["$key"]=
+ for argument in "$@"
+ '[' distro=alpine = -h ']'
+ '[' distro=alpine = --help ']'
++ echo distro=alpine
++ cut -f1 -d=
+ local key=distro
+ local key_length=6
+ local value=alpine
+ args["$key"]=alpine
+ for argument in "$@"
+ '[' desktop=xfce = -h ']'
+ '[' desktop=xfce = --help ']'
++ echo desktop=xfce
++ cut -f1 -d=
+ local key=desktop
+ local key_length=7
+ local value=xfce
+ args["$key"]=xfce
+++ dirname ./build_complete.sh
++ realpath -m .
+ base_dir=/home/[username]/shimboot
+ board=dedede
+ compress_img=
+ rootfs_dir=
+ quiet=
+ desktop=xfce
+ data_dir=
+ arch=amd64
+ release=
+ distro=alpine
+ arm_boards='
  corsola hana jacuzzi kukui strongbad nyan-big kevin bob
  veyron-speedy veyron-jerry veyron-minnie scarlet elm
  kukui peach-pi peach-pit stumpy daisy-spring trogdor
'
+ bad_boards='reef sand snappy pyro'
+ grep -q dedede
+ grep -q dedede
++ uname -m
+ kernel_arch=x86_64
+ host_arch=unknown
+ '[' x86_64 = x86_64 ']'
+ host_arch=amd64
+ needed_deps='wget python3 unzip zip git debootstrap cpio binwalk pcregrep cgpt mkfs.ext4 mkfs.ext2 fdisk depmod findmnt lz4 pv'
++ check_deps 'wget python3 unzip zip git debootstrap cpio binwalk pcregrep cgpt mkfs.ext4 mkfs.ext2 fdisk depmod findmnt lz4 pv'
++ local 'needed_commands=wget python3 unzip zip git debootstrap cpio binwalk pcregrep cgpt mkfs.ext4 mkfs.ext2 fdisk depmod findmnt lz4 pv'
++ for command in $needed_commands
++ command -v wget
++ for command in $needed_commands
++ command -v python3
++ for command in $needed_commands
++ command -v unzip
++ for command in $needed_commands
++ command -v zip
++ for command in $needed_commands
++ command -v git
++ for command in $needed_commands
++ command -v debootstrap
++ for command in $needed_commands
++ command -v cpio
++ for command in $needed_commands
++ command -v binwalk
++ for command in $needed_commands
++ command -v pcregrep
++ for command in $needed_commands
++ command -v cgpt
++ for command in $needed_commands
++ command -v mkfs.ext4
++ for command in $needed_commands
++ command -v mkfs.ext2
++ for command in $needed_commands
++ command -v fdisk
++ for command in $needed_commands
++ command -v depmod
++ for command in $needed_commands
++ command -v findmnt
++ for command in $needed_commands
++ command -v lz4
++ for command in $needed_commands
++ command -v pv
+ '[' '' ']'
+ '[' amd64 '!=' amd64 ']'
+ cleanup_path=
+ trap sigint_handler SIGINT
+ shim_url='https://dl.darkn.bio/api/raw/?path=/SH1mmer/dedede.zip'
+ boards_url='https://chromiumdash.appspot.com/cros/fetch_serving_builds?deviceCategory=ChromeOS'
+ '[' -z '' ']'
+ data_dir=/home/[username]/shimboot/data
+ print_title 'downloading list of recovery images'
+ printf '>> \033[1;32mdownloading list of recovery images\033[0m\n'
>> downloading list of recovery images
++ wget -qO- --show-progress 'https://chromiumdash.appspot.com/cros/fetch_serving_builds?deviceCategory=ChromeOS'
++ python3 -c '
import json, sys

all_builds = json.load(sys.stdin)
board_name = sys.argv[1]
if not board_name in all_builds["builds"]:
  print("Invalid board name: " + board_name, file=sys.stderr)
  sys.exit(1)
  
board = all_builds["builds"][board_name]
if "models" in board:
  for device in board["models"].values():
    if device["pushRecoveries"]:
      board = device
      break

reco_url = list(board["pushRecoveries"].values())[-1]
print(reco_url)
' dedede
Unknown option 'show-progress'
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib64/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
+ reco_url=
```
And I already have `wget` as the latest version. Also, `wget --help | grep 'show-progress'` doesn't give any output...

**Comment by SniverDaBest** [comment]
Looking more into this, the `Unknown option 'show-progress'` error is from wget. When I do `wget --show-progress` just to test, it throws that error.

**Comment by Raf128** [comment]
yes, show progress is only available on versions above i think 1.16 or smth like that. So try updating wget.

**Comment by SniverDaBest** [comment]
I have the latest version of wget. It *might* be a thing with the fedora version? However, I have my doubts about that.

**Comment by SniverDaBest** [comment]
Never mind, building wget from source fixed it. I don't think the Fedora version has the `--show-progress` feature.
